### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by irwsrs** [phr00t/AutoStepper#17]
Solved. Just needed to install audio drivers.

--

Hi, recently switched my server where I do this from Ubuntu to Arch. Previously worked fine, now getting this error.
 
Using java-14-openjdk, but also tried 11, 8 & 7. Overlooked dependencies or should be using a different Java package, or what might be going on? Finds the input dir/files fine. Error comes as soon as it begins processing.

```
Exception in thread "main" java.lang.
at autostepper.AutoStepper.analyzeUsingAudioRecordingStream(AutoStepper.java:
at autostepper.AutoStepper.main(AutoStepper.java:100)
```

Update: Works on my local Arch machine, same Java 14. So the server must be missing something. Any thoughts?

**Comment by rcMarty** [comment]
Had the same problem on WSL with Ubuntu 20 with ``openjdk version "11.0.13" 2021-10-19``. I ended on Windows on Java openjdk version "1.8.0-292"

WIndows:
```
> java -version
openjdk version "1.8.0-292"
OpenJDK Runtime Environment (build 1.8.0-292-b10)
OpenJDK 64-Bit Server VM (build 25.71-b10, mixed mode)
``` 
and works just fine

**Comment by avaer** [comment]
> Solved. Just needed to install audio drivers.

@irwsrs Could you be more specific?

I'm seeing this issue as well, on both windows WSL (Ubuntu OpenJDK) and Windows Java:

```
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\a\AutoStepper\dist> java -jar AutoStepper.jar input="./songs/" output="./lol/" hard=true
Starting AutoStepper by Phr00t's Software, v1.7 (See www.phr00t.com for more goodies!)
Processing directory: \\wsl$\Ubuntu\home\a\AutoStepper\dist\.\songs

[--- Processing 90.0s of nightcore.wav ---]
Exception in thread "main" java.lang.NullPointerException
        at autostepper.AutoStepper.analyzeUsingAudioRecordingStream(AutoStepper.java:267)
        at autostepper.AutoStepper.main(AutoStepper.java:100)
```

```
java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```

```
java -version
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) Client VM (build 25.361-b09, mixed mode, sharing)
```
