### ISSUE TITLE
add ability to skip unsupported file formats

### ISSUE THREAD

**Issue by Clonewayx** [phr00t/AutoStepper#3]
Add ability to skip unsupported file formats and continue to another one.

Error when FLAC is in working folder
```
[--- Processing 90.0s of 08 - Met Before.flac ---]
Exception in thread "main" java.lang.NullPointerException
	at autostepper.AutoStepper.analyzeUsingAudioRecordingStream(AutoStepper.java:267)
	at autostepper.AutoStepper.main(AutoStepper.java:100)
```

**Comment by phr00t** [comment]
FLAC is now properly skipped in v1.7
